version: '3.7'
services:
  app:
    volumes:
      - '.:/var/www/account-management-system'
    environment:
      - BILLING_SERVICE_ENDPOINT=http://localhost:3000/api
      - CHECKOUT_SUCCESS_REDIRECT_URL=https://mangomap.com
      - RECURLY_PUBLIC_KEY=sc-qddYBWkJNyoy3Ug6BD0ztt
      - CHECKOUT_QUIT_REDIRECT_URL=http://localhost:3000/plans
      - UPDATE_CARD_SUCCESS_REDIRECT_URL=http://localhost:3000/login
      - UPDATE_CARD_QUIT_REDIRECT_URL=http://localhost:3000/login
      - TEST_MODE=true
    command: ["npm", "run", "next:dev"]
volumes:
  maps-service-db-data:
